version: "3"
services:
  mongo:
    image: mongo:4

  mailchimp-sync-service:
    ports:
      - 80:80
    build: .
    volumes:
      - ./src/:/usr/src/app/src
    depends_on:
      - mongo
    environment:
      - RUN_MODE=job
